# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: yxdooo.VirtualBoxRPC
PackageVersion: 1.0.0
InstallerType: portable
Commands:
- VirtualBoxRPC
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/yxdooo/virtualbox-discord-rpc/releases/download/v1.0.0/VirtualBoxRPC.exe
  InstallerSha256: CF7C8FF08A391FD86AF86C2BE634305BEFAB4F00ECD66895695FC22FEB9FBAE3
ManifestType: installer
ManifestVersion: 1.6.0
