# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: yxdooo.VirtualBoxRPC
PackageVersion: 1.0.0
PackageLocale: en-US
Publisher: yxdooo
PublisherUrl: https://github.com/yxdooo
PublisherSupportUrl: https://github.com/yxdooo/virtualbox-discord-rpc/issues
PackageName: VirtualBox Discord Rich Presence
PackageUrl: https://github.com/yxdooo/virtualbox-discord-rpc
License: MIT
LicenseUrl: https://github.com/yxdooo/virtualbox-discord-rpc/blob/main/LICENSE
Copyright: Copyright (c) 2026 yxdooo
ShortDescription: High-performance Discord Rich Presence client for Oracle VM VirtualBox.
Description: Lightweight and non-intrusive Discord Rich Presence client for Oracle VM VirtualBox that tracks virtual machine execution, guest operating system distributions, and allocated hardware resources without locking background COM daemons. Includes native Windows startup integration and system tray controller.
Moniker: virtualbox-rpc
Tags:
- virtualbox
- discord
- discord-rpc
- rich-presence
- virtualization
- system-tray
ManifestType: defaultLocale
ManifestVersion: 1.6.0
